import os
from os.path import join as join
from argparse import ArgumentParser

def concat_seq(args):
	fa = ""
	write_file = open(join(args.output_dir, "genome.fasta"), 'w')
	for list_dir in os.listdir(args.input_dir):
		if os.path.exists(join(args.input_dir, list_dir, args.medaka_file_name)):
			for each_line in open(join(args.input_dir, list_dir, args.medaka_file_name)):
				fa = fa + each_line

	write_file.write(fa + '\n')
	write_file.close()
			

if __name__=="__main__":
	verbose = 0
	parser = ArgumentParser(description='Iter through each sample dirs generated by medaka and concatenate it to a single file')
	parser.add_argument('-d', '--input_dir', help='input directory file, i.e. medaka output directory', required=True)
	parser.add_argument('-m', '--medaka_file_name', help='by default : consensus.fasta from medaka output', required=True, type=str)
	parser.add_argument('-o', '--output_dir', help='output directory were the concatenate file to be saved', required=True)
	parser.add_argument('-f', '--output_file', help='output file name', required=True)
	args = parser.parse_args()
	concat_seq(args)
	
